name: CI

on:
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8.3.1

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18.20.0
          cache: 'pnpm'
        
      - name: Setup Biome CLI
        uses: biomejs/setup-biome@v2

      - name: Install pnpm
        run: npm install -g pnpm

      - name: Install dependencies
        run: pnpm install

      - name: Run Biome
        run: biome ci .

      - name: Run format
        run: pnpm format

      - name: Build the project
        run: pnpm build
